# Full environment

name: LLBG
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - cudatoolkit=11.3
  - pytorch=1.10.1
  - torchvision
  - matplotlib
  - scikit-learn
  - scikit-image
  - tensorboard
  - tensorflow
  - pip
  - scipy
  - pip:
      - hydra-core
      - kornia
      - lpips
      - timm
      - ortools
