name: large_batch_cifar

defaults:
  - data: CIFAR100
  - impl: default_windows
  - server: honest-but-curious
  - user: local_updates
  - _self_
model: MLP

# Server and user:
num_queries: 1

user:
  num_data_points: 100
