# @package _global_
# Configuration defaults
# Settings are separated into case, attack analysis
defaults:
  - case: 6.2_large_batch_cifar_win
  - attack: iterativedlbg
  - _self_
  - override hydra/job_logging: custom

base_dir: outputs
hydra:
  sweep:
    dir: ${base_dir}/${name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  run:
    dir: ${base_dir}/${name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
# To change output folder location:
# Set hydra.output_subdir=something
# searchpath:
#   - pkg://

seed: # Optional: Set initial seed
name: my_run # A name for this run [will be used for the summary table and outputs folder]

# debug implementation by running every loop just once:
dryrun: True

# When benchmarking:
num_trials: 100
save_reconstruction: True
